name: End-to-end tests
on:
  push:
    branches: [ cypress ]
  pull_request:
    branches: [ cypress ]

jobs:
  end-to-end-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
        working-directory: frontend
      - run: npm run start &
        working-directory: frontend
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install poetry
        working-directory: backend
      - run: poetry install
        working-directory: backend
      - run: poetry run python manage.py runserver &
        working-directory: backend
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: acceptance-tests
          wait-on: 'http://localhost:4200, http://localhost:8000'
          wait-on-timeout: 300